image_upload/base/urls.py
from django.urls import path
from image_upload.base import views


app_name = "base"
urlpatterns = [
    path("", views.home, name="home"),
    path("get_download_url/<str:filename>", views.get_download_url, name="download_url")
]

image_upload/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("image_upload.base.urls"))
]

image_upload/base/views.py
import requests
import logging
import boto3
from datetime import datetime

from django.shortcuts import render
from django.conf import settings
from django.http import JsonResponse

log = logging.getLogger(__name__)

s3_client = boto3.client(
    "s3", 
    aws_access_key_id=settings.AWS_ACCESS_KEY_ID, 
    aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY
)
bucket_name = settings.AWS_BUCKET_NAME


def home(request):
    filename = "no_file"

    if request.method == "POST":
        url = settings.API_GATEWAY_URL
        image = request.FILES.get("image")
        
        if not image:
            return render(request, "base/base.html", {"filename": filename})

        filename = image.name
        filename = f"{datetime.strftime(datetime.now(), '%Y%m%d_%H%M%S')}_{filename}"

        image_content = image.read()
        headers = {"Content-Type": "application/png"}

        try:
            requests.post(url, data=image_content, headers=headers, params={"filename": filename})
        except Exception as e:
            log.info(f"An exception was raised when trying to send the image to API-Gateway: {e}")
        
    return render(request, "base/base.html", {"filename": filename})


def get_download_url(request, filename):
    try:
        resp = s3_client.generate_presigned_url(
            'get_object', 
            Params={'Bucket': bucket_name, 'Key': f"resized/{filename}"}, 
            ExpiresIn=3000
        )
    except Exception as e:
        return JsonResponse({}, status=404)
    
    return JsonResponse({"url": resp})

image_upload/base/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {display: flex; height: 100dvh; flex-direction: column;}
        form {margin: auto; display: flex; flex-direction: column; text-align: center;}
        label {margin-bottom: 30px; font-size: x-large;}
        input {margin-bottom: 30px;}
        button {background-color: green; padding: 8px; border-radius: 8px; width: 150px; align-self: center; color: white; border: none;}
        button:hover {background-color: rgb(1, 173, 1); cursor: pointer;}
        #downloadUrl {background-color: green; padding: 5px; border-radius: 8px; width: 100px; align-self: center; color: white; display: none;}
        #downloadUrl:hover {background-color: rgb(1, 173, 1);}
    </style>
    <title>Form</title>
</head>
<body>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="image">Escolha uma imagem</label>
        <input type="file" id="image" name="image">
        <button type="submit">Redimensionar</button>
        <p id="downloadMessage"></p>
        <a id="downloadUrl" href=""></a>
    </form>

    <script>
        const downloadMessage = document.getElementById("downloadMessage")
        const urlElement = document.getElementById("downloadUrl")
        const fileName = '{{ filename }}';
        let executionCount = 0;
        const maxExecutions = 5;

        if (fileName !== "no_file") {
            downloadMessage.textContent = "Aguarde o link para download"
            let intervalId;
            function getUrl() {
                fetch('{% url "base:download_url" filename=filename %}', 
                    {"method": 'GET'})
                .then(response => {
                    if (response.ok) {
                        return response.text();
                    }
                })
                .then(data => {
                    if (JSON.parse(data).url) {
                        urlElement.textContent = "Download";
                        urlElement.href = JSON.parse(data).url;
                        downloadMessage.textContent = "";
                        urlElement.style.display = "unset";
                        clearInterval(intervalId);
                    }
                })

                executionCount++;
                if (executionCount >= maxExecutions) {
                    clearInterval(intervalId);
                }
            }

            intervalId = setInterval(getUrl, 8000);
        }
    </script>

</body>
</html>